data:
    type: "LLdataset"
    train_dataset: "Synthetic"
    val_dataset: "Synthetic"
    patch_size: 256
    channels: 3
    num_workers: 4
    #data_dir: "/data/Image_restoration/LL_dataset"
    data_dir: "/content/drive/My Drive/LOLI/LOLv2"
    ckpt_dir: "ckpt/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 8
    n_epochs: 5
    validation_freq: 1000

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
